# Generated by Django 5.0.6 on 2024-05-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="died"),
        ),
    ]
